# Generated by Django 6.0.6 on 2026-07-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="mobile",
            new_name="mobile_number",
        ),
    ]
