# Generated by Django 6.0.6 on 2026-07-03 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_mobile_customuser_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_pic",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must contain only numbers.",
                        regex="^\\d{1,15}$",
                    )
                ],
            ),
        ),
    ]
